
Warmup phase started

Training and Validation Results of Epoch Warmup-0:
================================
Training Loss Energy: 0.9848226141929627, Training Loss Force: 4.2199985122680665, time: 0.810265302658081
Validation Loss Energy: 0.0, Validation Loss Force: 0.0, time: 0

Traceback (most recent call last):
  File "/home/ws/fq0795/git/gnn_uncertainty/evaluate_models.py", line 99, in <module>
    mve.fit(epochs=epochs, warmup_steps=warmup_steps, train_loader=trainloader, valid_loader=validloader, device=device, dtype=torch.float32, use_wandb=use_wandb, patience=patience, model_path=model_path, force_weight=force_weight, energy_weight=energy_weight)
  File "/home/ws/fq0795/git/gnn_uncertainty/uncertainty/mve.py", line 40, in fit
    self.warmup(train_loader, optimizer, criterion, device, dtype, epochs=warmup_steps, force_weight=force_weight, energy_weight=energy_weight, log_interval=log_interval)
  File "/home/ws/fq0795/git/gnn_uncertainty/uncertainty/mve.py", line 104, in warmup
    self.epoch_summary(f"Warmup-{epoch}", False, lr)
  File "/home/ws/fq0795/git/gnn_uncertainty/uncertainty/mve.py", line 214, in epoch_summary
    logs.update(additional_logs)
TypeError: 'bool' object is not iterable
