/home/ws/fq0795/miniconda3/envs/torch/lib/python3.12/site-packages/torch/autograd/graph.py:744: UserWarning: Attempting to run cuBLAS, but there was no current CUDA context! Attempting to set the primary context... (Triggered internally at ../aten/src/ATen/cuda/CublasHandlePool.cpp:135.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
/home/ws/fq0795/miniconda3/envs/torch/lib/python3.12/site-packages/sklearn/utils/validation.py:1300: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
Traceback (most recent call last):
  File "/home/ws/fq0795/git/gnn_uncertainty/reevaluate_experiments.py", line 72, in <module>
    swag.calibrate_uncertainty(validationloader, device=device, dtype=torch.float32, path=f"{out_path}/calibration{i}.png")
  File "/home/ws/fq0795/git/gnn_uncertainty/uncertainty/base_uncertainty.py", line 289, in calibrate_uncertainty
    self.uncertainty_slope = linear.coef_[0][0]
                             ~~~~~~~~~~~~~~~^^^
IndexError: invalid index to scalar variable.
