Traceback (most recent call last):
  File "/home/ws/fq0795/git/gnn_uncertainty/reevaluate_experiments.py", line 64, in <module>
    mve.calibrate_uncertainty(testloader_in, device=device, dtype=torch.float32, path=f"{out_path}/calibration{i}.png")
  File "/home/ws/fq0795/git/gnn_uncertainty/uncertainty/base_uncertainty.py", line 311, in calibrate_uncertainty
    self.uncertainty_slope = linear.coef_[0]
                             ^^^^^^^^^^^^
AttributeError: 'RANSACRegressor' object has no attribute 'coef_'
